# Learning and Decision Making

## Laboratory 3: Markov decision problems

In the end of the lab, you should submit all code/answers written in the tasks marked as "Activity n. XXX", together with the corresponding outputs and any replies to specific questions posed to the e-mail <adi.tecnico@gmail.com>. Make sure that the subject is of the form [&lt;group n.&gt;] LAB &lt;lab n.&gt;.

### 1. Modeling

Consider once again the knight domain described in the Homework and which you described as a Markov decision process.

<img src="knight.png" width="200px">

Recall that:

* At each step, the knight may move in any of the four directions---up, down, left and right. 

* The movement succeeds with a 0.6 probability and fails with a 0.4 probability. When the movement fails, the knight may stay in the same cell or move to one of the immediately adjacent cells (if there is one) with equal probability.

* The goal of the knight is to save (reach) the princess and avoid the dragon.

**Throughout the lab, use $\gamma=0.99$.**

---

#### Activity 1.        

Implement your Markov decision process in Python. In particular,

* Create a list with all the states;
* Create a list with all the actions;
* For each action, define a `numpy` array with the corresponding transition probabilities;
* Define a `numpy`array with the costs. Make sure that:
    * The costs lie in the interval [0, 1]
    * The cost for standing in the princess's cell is minimal
    * The cost for standing in the dragon's cell is maximal
    * The costs for the intermediate cells are around 1/5 of those of standing in the dragon's cell

The order for the states and actions used in the transition probability and cost matrices should match that in the lists of states and actions. 

**Note**: Don't forget to import `numpy`.

---

In [26]:
import numpy as np

# Cria um MDP com os respetivos atributos.
# Certificar que a lista de acoes tem a mesma
# ordem que a lista com as matrizes de transicao.
def create_MDP(X, A, Pa, C):
    def create_trans_A(A, Pa):
        result = {}
        for i in range(len(A)):
            result[A[i]] = Pa[i]

        return result


    return  {"X": X, "A": A,\
             "Pa": create_trans_A(A,Pa), "C": C\
            }

def get_X(MDP):
    return MDP.get("X")

def get_A(MDP):
    return MDP.get("A")

# Devolve a Pa correspondente a acao pedida.
def get_Pa(MDP, a):
    return MDP.get("Pa").get(a)

def get_C(MDP):
    return MDP.get("C")

def print_MDP(MDP):
    print("O espaco de estados e:\n{}\n".format(get_X(MDP)))

    print("O espaco de acoes e:\n{}\n".format(get_A(MDP)))

    for el in get_A(MDP):
        print("A matriz de transicao associada a acao {} e:\n{}\n".format(el, get_Pa(MDP, el)))

    print("A matriz de custos tem segue a organizao do X e A, com os seguinte conteudo:\n{}\n".format(get_C(MDP)))

###     Matrizes de transicoes      ###
P_U =   [ [0.8, 0.1, 0, 0.1, 0, 0],
          [0.1, 0.7, 0.1, 0, 0.1, 0],
          [0, 0.1, 0.8, 0, 0, 0.1],
          [0.6, 0, 0, 0.3, 0.1, 0],
          [0, 0.6, 0, 0.1, 0.2, 0.1],
          [0, 0, 0.6, 0, 0.1, 0.3]
        ]
P_U = np.array(P_U)

P_L =   [ [0.8, 0.1, 0, 0.1, 0, 0],
          [0.6, 0.2, 0.1, 0, 0.1, 0],
          [0, 0.6, 0.3, 0, 0, 0.1],
          [0.1, 0, 0, 0.8, 0.1, 0],
          [0, 0.1, 0, 0.6, 0.2, 0.1],
          [0, 0, 0.1, 0, 0.6,0.3]
        ]
P_L = np.array(P_L)

P_D = np.flip(np.flip(P_U, 1), 0)
P_R = np.flip(np.flip(P_L, 1), 0)

###     Espaco de transicoes      ###

X = [ (0, 0), (0, 1), (0, 2),\
      (1, 0), (1, 1), (1, 2)
    ]

###     Accoes e Pa      ###

A = ["U", "D", "L", "R"]

Pa = [P_U, P_D, P_L, P_R]

###     Custos      ###

C = [   [0.2, 0.2, 0.2, 0.2],   #1
        [0.2, 0.2, 0.2, 0.2],   #2
        [0.2, 0.2, 0.2, 0.2],   #3
        [0.2, 0.2, 0.2, 0.2],   #4
        [1, 1, 1, 1],   #5
        [0, 0, 0, 0],   #6
    ]

C = np.array(C)

MDP = create_MDP(X, A, Pa, C)

print_MDP(MDP)


O espaco de estados e:
[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2)]

O espaco de acoes e:
['U', 'D', 'L', 'R']

A matriz de transicao associada a acao U e:
[[ 0.8  0.1  0.   0.1  0.   0. ]
 [ 0.1  0.7  0.1  0.   0.1  0. ]
 [ 0.   0.1  0.8  0.   0.   0.1]
 [ 0.6  0.   0.   0.3  0.1  0. ]
 [ 0.   0.6  0.   0.1  0.2  0.1]
 [ 0.   0.   0.6  0.   0.1  0.3]]

A matriz de transicao associada a acao D e:
[[ 0.3  0.1  0.   0.6  0.   0. ]
 [ 0.1  0.2  0.1  0.   0.6  0. ]
 [ 0.   0.1  0.3  0.   0.   0.6]
 [ 0.1  0.   0.   0.8  0.1  0. ]
 [ 0.   0.1  0.   0.1  0.7  0.1]
 [ 0.   0.   0.1  0.   0.1  0.8]]

A matriz de transicao associada a acao L e:
[[ 0.8  0.1  0.   0.1  0.   0. ]
 [ 0.6  0.2  0.1  0.   0.1  0. ]
 [ 0.   0.6  0.3  0.   0.   0.1]
 [ 0.1  0.   0.   0.8  0.1  0. ]
 [ 0.   0.1  0.   0.6  0.2  0.1]
 [ 0.   0.   0.1  0.   0.6  0.3]]

A matriz de transicao associada a acao R e:
[[ 0.3  0.6  0.   0.1  0.   0. ]
 [ 0.1  0.2  0.6  0.   0.1  0. ]
 [ 0.   0.1  0.8  0.   0.   0.1]
 [ 0.1  0

### 2. Prediction

You are now going to evaluate a given policy, computing the corresponding cost-to-go.

---

#### Activity 2.

Describe the policy that, in each state $x$, always moves the knight to the cell closest to the princess (irrespectively of the dragon). If multiple such cells exist, the knight should select randomly between the two.

For example, suppose that the knight is in cell 1. The knight should then select randomly between the actions _D_ and _R_. Conversely, suppose that the knight is in cell 4. The knight should then select actions _R_ with probability 1.

**Note:** The policy should be described as a vector with as many rows as there are states and as many columns as there are actions, where the entry _xa_ has the probability of selecting action _a_ in state _x_.

---

In [27]:
# Relembrar que a ordem das acoes é  U D L R

policy_2 = [[0, 0.5, 0, 0.5], #1
            [0, 0.5, 0, 0.5], #2
            [0, 1, 0, 0], #3
            [0, 0, 0, 1], #4
            [0, 0, 0, 1], #5
            [0, 0.5, 0, 0.5], #6
        ]
policy_2 = np.array(policy_2)

---

#### Activity 3.

Compute the cost-to-go function $J^\pi$ associated with the policy from Activity 2.

---

In [54]:
gama = 0.99


def compute_CPI(cost, pi):
    cpi = np.zeros(len(pi))
    
    for line in range(len(pi)):
        
        result = 0
        
        for columm in range(len(cost[0])):
            result += pi[line][columm]*cost[line][columm]
        
        cpi[line] = result
    
    return cpi

def transition_prob_pi(pi):
    space_state = len(get_X(MDP))
    
    ppi = np.zeros((space_state,space_state))
    
    for line in range(space_state):
        for columm in range(space_state):
            result = 0
            
            for a in range(len(get_A(MDP))):
                el = get_A(MDP)[a]
                result += pi[line][a]*get_Pa(MDP, el)[line][columm]
            ppi[line][columm] = result
    
    return ppi

cpi = compute_CPI(get_C(MDP), policy_2)
ppi = transition_prob_pi(policy_2)
j_pi = np.dot(np.linalg.inv((np.identity(len(policy_2))-(gama*ppi))), cpi)

print("O Jpi é:")
print(j_pi)



O Jpi é:
[ 16.26056701  15.95826371  15.28584405  16.45495016  16.42766638
  15.09441121]


### 3. Control

In this section you are going to compare value and policy iteration, both in terms of time and number of iterations.

---

#### Activity 4

Show that the policy in Activity 3 is _not_ optimal: use value iteration to compute $J^*$ and show that $J^*\neq J^\pi$. Track the time and the number of iterations taken to compute $J^*$.

**Note 1:** Stop the algorithm when the error between iterations is smaller than $10^{-8}$.

**Note 2:** You may find useful the function ``time()`` from the module ``time``.

---

In [49]:
import time as t
        
    
#operator H
def H(Q):
    Qnew=np.zeros((len(get_X(MDP)), len(get_A(MDP))))
    minQ=np.amin(Q,axis=1)

    numb_of_actions = len(get_A(MDP))
    for a in range(numb_of_actions):
        el = get_A(MDP)[a]
        Qnew[:,a] = get_C(MDP)[:,a] + gama*np.dot(get_Pa(MDP, el), minQ)         
    return Qnew
    
def matrixQ():
    diference = 1e-8
    Q0=np.zeros((len(get_X(MDP)), len(get_A(MDP)))) 
    i=0
    eps=1
    while(eps > diference):
        Qaux=H(Q0)
        eps=np.linalg.norm(np.subtract(Qaux,Q0),np.inf)
        i+=1
        Q0=Qaux
    return Qaux,i
    
    
t_s = t.time()
J_optimal, iterations = matrixQ()
t_f = t.time()

J1=np.amin(J_optimal,axis=1,keepdims=True)

print("The numb of iterations is: {}\nThe time was: {}".format(iterations, (t_f-t_s)))

print("The J* i:\n{}".format(J_optimal))

for i in range(4):
    print(".")

print(J1)


print("\nComo é possivel ver o J* é diferente do Jpi, pois todas as linhas do J* são melhores que o Jpi, tal como era esperado.")

The numb of iterations is: 1775
The time was: 0.05092501640319824
The J* i:
[[ 14.13225758  14.22137619  14.13225758  14.0679709 ]
 [ 14.06608201  14.4665994   14.13036869  13.93809883]
 [ 13.75354791  13.67954694  13.8815311   13.75354791]
 [ 14.2480085   14.33712711  14.33712711  14.58423921]
 [ 14.94920902  15.34972641  15.1026143   14.74722486]
 [ 13.604051    13.53005003  14.13255157  13.53005003]]
.
.
.
.
[[ 14.0679709 ]
 [ 13.93809883]
 [ 13.67954694]
 [ 14.2480085 ]
 [ 14.74722486]
 [ 13.53005003]]

Como é possivel ver o J* é diferente do Jpi, pois todas as linhas do J* são melhores que o Jpi, tal como era esperado.


---

#### Activity 5

Compute once again the optimal policy now using policy iteration. Track the time and number of iterations taken and compare to those of Activity 4.

**Note:** If you find that numerical errors affect your computations (especially when comparing two values/arrays) you may use the `numpy` function `isclose` with adequately set absolute and relative tolerance parameters (e.g., $10^{-8}$).

---

In [22]:
def construct_J(PPi,costPi):
    id = np.eye(len(get_X(MDP)))
    return np.dot(np.linalg.inv(id - (gama*PPi)),costPi)

def greedy(J):
    c=np.zeros((len(get_X(MDP)), len(get_A(MDP))))
    for a in range(len(get_A(MDP))):
        el = get_A(MDP)[a]
        c[a] = get_C(MDP)[:,a] + gama * get_Pa(MDP, el).dot(J)[:,0]
    new=np.amin(c,axis=1,keepdims=True)
    return c

def policy_iteration2():
    k = 0
    stop = False
    m_policy = np.ones((len(get_X(MDP)), len(get_A(MDP))))
    
    while not stop:
        
        #Policy evaluation
        cpi = compute_CPI(get_C(MDP), m_policy)
        ppi = transition_prob_pi(m_policy)

        J= construct_J(ppi,cpi)

        #Q funcion
        Q = np.zeros((len(get_X(MDP)), len(get_A(MDP))))
        #greedy J
        for i in range(len(get_A(MDP))):
            el = get_A(MDP)[i]
            Q[:,i] = get_C(MDP)[:,i] + gama * get_Pa(MDP, el).dot(J)
    
        #improved policy
        new_policy = np.zeros((len(get_X(MDP)), len(get_A(MDP))))

        
        for a in range(len(get_A(MDP))):

            new_policy[:,a] = np.isclose(Q[:,a],np.amin(Q, axis=1),atol=1e-8, rtol=1e-8).astype(int)

        new_policy =new_policy/np.sum(new_policy,axis=1, keepdims =True)

        #update loop
        stop = (m_policy ==new_policy).all()
        m_policy =new_policy
        k +=1
    return m_policy, k

ti=t.time()
iteration_policy = policy_iteration2()
tf=t.time()-ti

print("J* is given by:")
print(iteration_policy[0])

print("The number of iterations was: ", iteration_policy[1], "a and took time: ",tf)

J* is given by:
[[ 0.   0.   0.   1. ]
 [ 0.   0.   0.   1. ]
 [ 0.   1.   0.   0. ]
 [ 1.   0.   0.   0. ]
 [ 0.   0.   0.   1. ]
 [ 0.   0.5  0.   0.5]]
The number of iterations was:  4 a and took time:  0.0


### 4. Simulation

Finally, in this section you will check whether the theoretical computations of the cost-to-go actually correspond to the cost incurred by an agent following a policy.

---

#### Activity 6

Starting both in cell 1 and cell 5 in the figure, 

* Generate **100** trajectories of 10,000 steps each, following the optimal policy for the MDP. 
* For each trajectory, compute the accumulated (discounted) cost. 
* Compute the average cost over the 100 trajectories.
* Compare the resulting value with that computed in Activity 4 for the two states. 

** Note:** The simulation may take a bit of time, don't despair ☺️.

---

In [62]:
def inicializate_matrix(x_val, y_val):
    matrix = []
    return [x[:] for x in [[matrix] * x_val] * y_val]


def creatPath(i_State, steps):
    mCost = get_C(MDP)
    all_states = get_X(MDP)
    
    cost = 0
    path = [i_State]
    
    a_size = len(get_A(MDP))
    x_size = len(get_X(MDP))
    all_states = get_X(MDP)
    
    #policyM = policy_2
    policyM = iteration_policy[0]
    
    #works on the state
    for i in range(steps):
        last_state_index= all_states.index(path[-1])
        rand_action = np.random.choice(len(get_A(MDP)), 1, p=policyM[last_state_index])[0]
        el = get_A(MDP)[rand_action]
        
        next_state = np.random.choice(x_size,1,p=get_Pa(MDP, el)[last_state_index])[0]
        path.append(all_states[next_state])
       
        cost +=mCost[last_state_index][rand_action]*gama**i
    return path, cost

def act6(i_State, steps, traj):
    cost_average =0
    for i in range(traj):
        cost_average += creatPath(i_State, steps)[1]
    return cost_average/traj

print("O valor teorico de 1 é: {}\nO valor teorico de 5 é: {}\nO J* é:".format(J1[0],J1[4]))
print(J1)

print("Vai levar o seu tempo")
print("Para o estado 1 é: {}\nPara o estado 5 é: {}\n".format(act6((0,0),10000,100),act6((1,1),10000,100))) 

print("O valor experimental nesta questão aproxima-se do valor teorica no exercicio 3.4.\n")



O valor teorico de 1 é: [ 14.0679709]
O valor teorico de 5 é: [ 14.74722486]
O J* é:
[[ 14.0679709 ]
 [ 13.93809883]
 [ 13.67954694]
 [ 14.2480085 ]
 [ 14.74722486]
 [ 13.53005003]]
Vai levar o seu tempo
Para o estado 1 é: 14.143648991293643
Para o estado 5 é: 14.474112743827652

O valor experimental nesta questão aproxima-se do valor teorica no exercicio 3.4.

